/*
 * This source file was generated by the Gradle 'init' task
 */
package project.main;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void appHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
